### ISSUE TITLE
Align Edit / Delete icons in Calendar

### ISSUE THREAD

**Issue by bakhshiqbal** [bakhshiqbal/collegeknight#15]
the edit and delete icons on the course are sligtly mis aligned, I think the delete icon is correctly aligned with the text and the edit icon needs adjustment, do you also have the same view?

**Comment by sairajaved** [comment]
fixed,please verify

**Comment by bakhshiqbal** [comment]
@sairajaved I still see these misaligned. 
![screen shot 2018-09-27 at 9 41 58 pm](https://user-images.githubusercontent.com/36213859/46183317-6df20900-c29e-11e8-960d-7dc8674bdd76.png)

**Comment by sairajaved** [comment]
Press ctrl+f5 or use incognito

**Comment by bakhshiqbal** [comment]
@sairajaved have these changes been pushed to production. Maybe it is a test environment thing? I tried on two browsers (Firefox and Safari) and two devices but still do not see the changes.
